version: "3.9"

services:
    postgres:
        container_name: postgres
        restart: always
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: example
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
    api:
        image: golang:1.16
        container_name: todolist-api
        working_dir: /src/cmd/api
        command: go run main.go
        environment: 
            DATABASE_URL: postgres://postgres:example@postgres:5432/todo?sslmode=disable
        ports:
            - "8080:8080"
        volumes:
            - gopath:/go
            - ./:/src

volumes:
    postgres-data:
        driver: local
    gopath:
        driver: local
